// AlternateStreamOverlay.idl : IDL source for AlternateStreamOverlay
//

// To be honest, there's no need to keep any of the default interfaces / typelibrary
// but I'm leaving in, incase I need them later.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(CFC72A5F-E58B-43BD-8968-BA89AFB2240D),
	helpstring("IAlternateStreamOverlayIcon Interface"),
	pointer_default(unique)
]
interface IAlternateStreamOverlayIcon : IUnknown{
};
[
	object,
	uuid(96296677-6A18-4F22-AC2E-84A650C4081D),
	helpstring("IAlternateStreamContext Interface"),
	pointer_default(unique)
]
interface IAlternateStreamContext : IUnknown{
};
[
	uuid(C0034A83-7FA3-43A7-82DD-3ADF66F0086C),
	version(1.0),
	helpstring("AlternateStreamOverlay 1.0 Type Library")
]
library AlternateStreamOverlayLib
{
	importlib("stdole2.tlb");
	[
		uuid(FBAB8C58-59C9-4522-B7E8-1A6AA23B318C),
		helpstring("AlternateStreamOverlayIcon Class")
	]
	coclass AlternateStreamOverlayIcon
	{
		[default] interface IAlternateStreamOverlayIcon;
	};
	[
		uuid(4A26024B-5499-45BE-A23F-4A65E88888D0),
		helpstring("AlternateStreamContext Class")
	]
	coclass AlternateStreamContext
	{
		[default] interface IAlternateStreamContext;
	};
};
